---

- name: copy sources.list
  become: true
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644

- name: install mandatory packages
  become: true
  apt:
    name: "{{ apt_mandatory_packages }}"
    update_cache: yes
    state: present
  notify: apt changed
  tags: packages

- name: disable unattended upgrades
  become: true
  lineinfile:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: "^{{ item.key }}"
    line: "{{ item.value }}"
  with_dict:
    'APT::Periodic::Update-Package-Lists': 'APT::Periodic::Update-Package-Lists "0";'
    'APT::Periodic::Unattended-Upgrade': 'APT::Periodic::Unattended-Upgrade "0";'
