---
# vim: set ft=ansible:


- name: install devpi server
  become: true
  pip:
    name:
      - devpi-server
      - devpi-client
    state: latest
    executable: pip3
  tags: update
  notify: restart devpi

- name: install devpi client
  become: true
  pip:
    name: devpi-client
    state: latest
  tags: update

- name: initialize devpi server dir
  become: true
  command: devpi-server --serverdir {{ devpi.dir | quote }} --init
  args:
    creates: "{{ devpi.dir }}"

- name: install systemd service for devpi
  become: true
  template:
    src: devpi.service.j2
    dest: /etc/systemd/system/devpi.service
    owner: root
    group: root
    mode: 0644
  notify: restart devpi

- name: ensure devpi is started
  become: true
  systemd:
    name: devpi.service
    daemon_reload: yes
    enabled: yes
    state: started

- name: copy dev server config
  become: true
  template:
    src: devpi-nginx.conf.j2
    dest: /etc/nginx/sites-available/devpi
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: symlink dev server to sites enabled
  become: true
  file:
    src: /etc/nginx/sites-available/devpi
    dest: /etc/nginx/sites-enabled/devpi
    state: link
  notify: restart nginx

- name: use local pypi
  command: devpi use http://{{ devpi.host }}:{{ devpi.local_port }}/root/pypi

- name: create config dirs
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/.buildout
    - ~/.config/pip

- name: generate .pydistutils.cfg
  template:
    src: devpi-pydistutils.cfg.j2
    dest: ~/.distutils.cfg
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: generate buildout default config
  template:
    src: devpi-buildout.cfg.j2
    dest: ~/.buildout/default.cfg
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: generate pip config
  template:
    src: devpi-pip.conf.j2
    dest: ~/.config/pip/pip.conf
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
