---
# vim: set ft=ansible:


- name: install shell integration for zsh
  shell: |
    curl -sfL https://iterm2.com/shell_integration/install_shell_integration_and_utilities.sh |
    zsh
  args:
    warn: no
