---
# vim: set ft=ansible:


- name: add neovim repository
  become: true
  apt_repository:
    repo: ppa:neovim-ppa/unstable
    state: present
    filename: neovim
    update_cache: yes

- name: install neovim
  become: true
  apt:
    name: neovim
    state: present

- name: install support for ruby plugins
  become: true
  gem:
    name: neovim
    user_install: no
    state: latest

- name: create vim directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - ~/.vim/autoload
  - ~/.local/share/nvim/site/autoload

- name: download vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ item }}"
  with_items:
  - ~/.vim/autoload/plug.vim
  - ~/.local/share/nvim/site/autoload/plug.vim

- name: create pyenvs for neovim
  command: >
    /usr/bin/zsh -ic
    "pyenv virtualenv {{ item.value | quote }} {{ item.key | quote }}"
  register: pyenv_create
  failed_when: >
    pyenv_create.rc != 0 and 'already exists' not in pyenv_create.stderr
  with_dict:
    neovim2: "{{ pyenv_python2 }}"
    neovim3: "{{ pyenv_python3 }}"

- name: create directory for neovim pythons
  file:
    path: ~/.neovim_pythons
    state: directory

- name: link pythons into neovim directories
  file:
    path: "~/.neovim_pythons/{{ item }}"
    src: "~/.pyenv/versions/neovim{{ item }}"
    state: link
  with_items:
  - 2
  - 3

- name: install neovim package into pythons
  command: >
    /usr/bin/zsh -ic 'pyenv activate {{ item }} && pip install -U neovim'
  with_items:
  - neovim2
  - neovim3

- name: install neovim plugins
  command: nvim --headless -c {{ item | quote }} -c 'qall!'
  with_items:
  - PlugUpdate
  - UpdateRemotePlugins
