---

- name: add neovim repository
  become: true
  apt_repository:
    repo: ppa:neovim-ppa/stable
    state: present
    filename: neovim
    update_cache: yes

- name: install neovim
  become: true
  apt:
    name: neovim
    state: present
  notify: apt changed

- name: create vim directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/.vim/autoload
    - ~/.local/share/nvim/site/autoload

- name: download vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ item }}"
  loop:
    - ~/.vim/autoload/plug.vim
    - ~/.local/share/nvim/site/autoload/plug.vim

- name: create directory for neovim pythons
  file:
    path: ~/.neovim_pythons
    state: directory

- name: create python2 env for neovim
  command: >
    bash -c 'source ~/.asdf/asdf.sh && virtualenv -p $(which python2) --download ~/.neovim_pythons/2'
  args:
    creates: "~/.neovim_pythons/2"

- name: create python3 env for neovim
  command: >
    bash -c 'source ~/.asdf/asdf.sh && python3 -m venv ~/.neovim_pythons/3'
  args:
    creates: "~/.neovim_pythons/3"

- name: install neovim package into pythons
  pip:
    name: pynvim
    state: latest
    virtualenv: "~/.neovim_pythons/{{ item }}"
  loop:
    - 2
    - 3

- name: install neovim plugins
  command: nvim --headless -c {{ item | quote }} -c 'qall!'
  loop:
    - PlugUpgrade
    - PlugUpdate
    - UpdateRemotePlugins
    - CocUpdateSync
