---
# vim: set ft=ansible:

- name: copy nginx global config
  become: true
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: remove default alias
  become: true
  file:
    path: "/etc/nginx/{{ item }}/default"
    state: absent
  with_items:
    - sites-enabled
    - sites-available
  notify: restart nginx
