---
# vim: set ft=ansible:


- name: add nodejs apt keys
  become: true
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
  - https://deb.nodesource.com/gpgkey/nodesource.gpg.key
  - https://dl.yarnpkg.com/debian/pubkey.gpg

- name: add nodejs repositories
  become: true
  apt_repository:
    repo: deb https://deb.nodesource.com/node_8.x {{ ansible_distribution_release }} main
    filename: nodejs
    state: present
    update_cache: yes

- name: add yarn repositories
  become: true
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present
    filename: yarn
    update_cache: yes

- name: install nodejs
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - nodejs
  - yarn
  notify: apt changed

- name: install npm packages
  npm:
    name: "{{ item }}"
    state: latest
    global: yes
  with_items: "{{ npm_mandatory_packages }}"

- name: install eslintrc global config
  template:
    src: eslintrc.yml.j2
    dest: ~/.eslintrc.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
