---

- name: add nodejs apt keys
  become: true
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: add nodejs repositories
  become: true
  apt_repository:
    repo: deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main
    filename: nodejs
    state: present
    update_cache: yes

- name: install nodejs
  become: true
  apt:
    name: nodejs
    state: present
  notify: apt changed
  tags: packages

- name: copy npmrc
  template:
    src: npmrc.j2
    dest: ~/.npmrc
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: create node prefix directory
  file:
    path: "{{ ansible_user_dir }}/.node_prefix"
    state: directory
