---

- name: copy npmrc
  template:
    src: npmrc.j2
    dest: ~/.npmrc
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: create node prefix directory
  file:
    path: "{{ ansible_user_dir }}/.node_prefix"
    state: directory
