---

- name: clone pyenv
  git:
    repo: https://github.com/yyuu/pyenv.git
    dest: ~/.pyenv
    version: master

- name: install pyenv plugins
  git:
    repo: "{{ item.repo }}"
    dest: "~/.pyenv/plugins/{{ item.name }}"
    version: master
  loop: "{{ pyenv.plugins }}"

- name: install pyenv pythons
  command: /usr/bin/zsh -ic 'pyenv install {{ item }}'
  args:
    creates: "~/.pyenv/versions/{{ item }}"
  loop: "{{ pyenv_pythons }}"
