---
# vim: set ft=ansible:


- name: clone pyenv
  git:
    repo: https://github.com/yyuu/pyenv.git
    dest: "~{{ ansible_user }}/.pyenv"
    version: master

- name: install pyenv plugins
  git:
    repo: "{{ item.repo }}"
    dest: "~{{ ansible_user }}/.pyenv/plugins/{{ item.name }}"
    version: master
  with_items: "{{ pyenv_plugins }}"

- name: install pyenv pythons
  command: /usr/bin/zsh -ic 'pyenv install -s {{ item | quote }}'
  with_items: "{{ pyenv_pythons }}"

- name: install default packages
  template:
    src: default-packages.j2
    dest: ~/.pyenv/default-packages
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
