---
# vim: set ft=ansible:


- name: download rustup installer
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup.sh
    mode: 0755
  register: rustup_installer
  when: not("~/.cargo/bin/rustup" | exists)

- name: install rustup
  command: /tmp/rustup.sh -y --no-modify-path
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rustup"

- name: rustup self update
  command: ~/.cargo/bin/rustup self update
  changed_when: false

- name: download stable rust
  command: ~/.cargo/bin/rustup install stable
  changed_when: false

- name: use stable rust
  command: ~/.cargo/bin/rustup default stable
  changed_when: false

- name: update rust
  command: ~/.cargo/bin/rustup update
  changed_when: false
  tags: packages

- name: install cargo packages
  command: ~/.cargo/bin/cargo install "{{ item.key | quote }}"
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/{{ item.value }}"
  with_dict: "{{ cargo_packages }}"
  tags: packages

- name: update existing packages
  command: ~/.cargo/bin/cargo install-update "{{ item.key | quote }}"
  with_dict: "{{ cargo_packages }}"
  tags: update
