---

- name: set shell
  become: true
  user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/fish

- name: install fisher
  command: fish -P -c 'curl -sL https://git.io/fisher | source; fisher update'
  args:
    creates: ~/.config/fish/conf.d
