---
# vim: set ft=ansible:


- name: set shell
  become: true
  user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh

- name: update antigen
  command: /usr/bin/zsh -ic 'antigen {{ item | quote }}'
  with_items:
  - update
  - cleanup

- name: copy tmux italic
  copy:
    src: tmux256-colors-italic
    dest: /tmp/tmux256-colors-italic

- name: install tmux italic
  command: tic /tmp/tmux256-colors-italic

- name: remove tmux italic temporary file
  file:
    path: /tmp/tmux256-colors-italic
    state: absent
