---

- name: install mandatory snaps
  become: true
  snap:
    name: "{{ item.key }}"
    classic: "{{ item.value.classic }}"
    channel: "{{ item.value.channel }}"
  with_dict: "{{ snap_mandatory_packages }}"
