---
# vim: set ft=ansible:


- name: create ssh config.d directory
  file:
    path: ~/.ssh/config.d
    state: directory

- name: create ssh socket directory
  file:
    path: ~/.ssh/sockets
    state: directory

- name: find out the keys to copy
  local_action: command find ~/.ssh -name 'id_*' -type f
  register: ssh_key_paths

- name: copy ssh keys from the local machine
  copy:
    src: "{{ item }}"
    dest: ~/.ssh
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0400
  with_items: "{{ ssh_key_paths.stdout_lines }}"

- name: copy common part of ssh config
  template:
    src: ssh-config-common.j2
    dest: ~/.ssh/config.d/99-common
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
  notify: ssh config parts
