---

- name: restart timesyncd
  become: true
  systemd:
    daemon_reload: yes
    name: systemd-timesyncd
    state: restarted
    enabled: yes

- name: zsh config parts
  assemble:
    src: ~/.zshrc.private.d
    dest: ~/.zshrc.private
    delimiter: "\n\n"

- name: assemble ssh config
  assemble:
    src: ~/.ssh/config.d
    dest: ~/.ssh/config
    delimiter: "\n\n"
  listen: ssh config parts

- name: apt autoremove
  become: true
  command: apt autoremove --yes --purge
  listen: apt changed

- name: apt clean
  become: true
  command: apt clean
  listen: apt changed

- name: restart docker
  become: true
  systemd:
    daemon_reload: yes
    name: docker
    state: restarted
    enabled: yes
