---
# vim: set ft=ansible:


- name: restart timesyncd
  become: true
  systemd:
    daemon_reload: yes
    name: systemd-timesyncd
    state: restarted
    enabled: yes

- name: restart docker
  become: true
  systemd:
    daemon_reload: yes
    name: docker
    state: restarted
    enabled: yes

- name: docker system prune
  become: true
  command: docker system prune -f
  args:
    warn: no
  listen: docker new images

- name: generate ssh config
  assemble:
    src: ~/.ssh/config.d
    dest: ~/.ssh/config
    delimiter: "\n\n"
  listen: ssh config parts
