---
# vim: set ft=ansible:


- name: assemble ssh config
  assemble:
    src: ~/.ssh/config.d
    dest: ~/.ssh/config
    delimiter: "\n\n"

- name: remove old known_hosts files
  file:
    path: "~/.ssh/{{ item }}"
    state: absent
  with_items:
  - known_hosts
  - known_hosts.old

- name: add mandatory ssh hosts
  shell: ssh-keyscan -T 10 -H {{ item | quote }} >> known_hosts
  args:
    chdir: ~/.ssh
  with_items: "{{ known_ssh_hosts }}"

- name: add hostnames from ssh config
  shell: >
    awk '/\s*HostName/ {print $2}' config
    | sort -u
    | xargs -r -n 1 ssh-keyscan -T 10 -H
    >> known_hosts
  args:
    chdir: ~/.ssh
